-- CREATE DATABASE zephyr;
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
	CUSTOMER_ID INT PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(100),
	AGE_BAND VARCHAR(20),
	REGION VARCHAR(50),
	CUSTOMER_SEGMENT VARCHAR(50),
	KYC_VERIFIED BOOLEAN,
	ACCOUNT_OPEN_DATE DATE
);

-- COPY dim_customer
-- FROM 'E:\\Projects\\data dna\\DataDNA Dataset Challenge - 2026-06 - UK Fintech Neobank Digital Transaction Health Monitor\\data\\dim_customer.csv'
-- WITH (
--   FORMAT   csv,
--   HEADER,
--   DELIMITER ',',
--   ENCODING 'WIN1252'   
-- );
CREATE TABLE IF NOT EXISTS DIM_MERCHANT_CATEGORY (
	MERCHANT_CATEGORY_ID INT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(100),
	SECTOR VARCHAR(50),
	RISK_FLAG VARCHAR(20)
);

-- COPY dim_merchant_category
-- FROM 'E:\\Projects\\data dna\\DataDNA Dataset Challenge - 2026-06 - UK Fintech Neobank Digital Transaction Health Monitor\\data\\dim_merchant_category.csv'
-- WITH (
--   FORMAT   csv,
--   HEADER,
--   DELIMITER ',',
--   ENCODING 'WIN1252'   
-- );
CREATE TABLE IF NOT EXISTS DIM_TRANSACTION_TYPE (
	TRANSACTION_TYPE_ID INT PRIMARY KEY,
	TYPE_NAME VARCHAR(50),
	CHANNEL VARCHAR(50),
	IS_DOMESTIC BOOLEAN,
	TYPICAL_FEE_GBP NUMERIC(10, 2)
);

-- COPY dim_transaction_type
-- FROM 'E:\\Projects\\data dna\\DataDNA Dataset Challenge - 2026-06 - UK Fintech Neobank Digital Transaction Health Monitor\\data\\dim_transaction_type.csv'
-- WITH (
--   FORMAT   csv,
--   HEADER,
--   DELIMITER ',',
--   ENCODING 'WIN1252'   
-- );


CREATE TABLE IF NOT EXISTS TRANSACTIONS (
	TRANSACTION_ID INT PRIMARY KEY,
	CUSTOMER_ID INT,
	TRANSACTION_TYPE_ID INT,
	MERCHANT_CATEGORY_ID INT,
	TRANSACTION_DATE VARCHAR(20),
	TRANSACTION_DATETIME TEXT,
	AMOUNT_GBP NUMERIC(12, 2),
	FEE_CHARGED_GBP NUMERIC(10, 2),
	TRANSACTION_STATUS VARCHAR(30),
	IS_FLAGGED_FRAUD BOOLEAN,
	FX_RATE_USED NUMERIC(10, 4),
	DEVICE_TYPE VARCHAR(50),
	FAILED_REASON VARCHAR(255)
);

-- COPY transactions
-- FROM 'E:\\Projects\\data dna\\DataDNA Dataset Challenge - 2026-06 - UK Fintech Neobank Digital Transaction Health Monitor\\data\\fact_transactions_updated.csv'
-- WITH (
--   FORMAT   csv,
--   HEADER,
--   DELIMITER ',',
--   ENCODING 'WIN1252'   
-- );

ALTER TABLE TRANSACTIONS
ADD COLUMN TRANSACTIONDATE DATE;

UPDATE TRANSACTIONS
SET
	TRANSACTIONDATE = CASE
		WHEN SPLIT_PART(TRANSACTION_DATE, '/', 1)::INT > 12 THEN TO_DATE(TRANSACTION_DATE, 'DD/MM/YYYY')
		ELSE TO_DATE(TRANSACTION_DATE, 'MM/DD/YYYY')
	END;

CREATE TABLE FACT_TRANSACTIONS AS
SELECT
	T.TRANSACTION_ID,
	T.TRANSACTIONDATE,
	T.TRANSACTION_DATETIME,
	T.AMOUNT_GBP,
	T.FEE_CHARGED_GBP,
	T.TRANSACTION_STATUS,
	T.IS_FLAGGED_FRAUD,
	T.DEVICE_TYPE,
	T.FX_RATE_USED,
	T.FAILED_REASON,
	TT.TRANSACTION_TYPE_ID,
	TT.TYPE_NAME,
	TT.CHANNEL,
	TT.IS_DOMESTIC,
	TT.TYPICAL_FEE_GBP,
	MC.MERCHANT_CATEGORY_ID,
	MC.CATEGORY_NAME,
	MC.SECTOR,
	MC.RISK_FLAG,
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME,
	C.AGE_BAND,
	C.REGION,
	C.CUSTOMER_SEGMENT,
	C.KYC_VERIFIED,
	C.ACCOUNT_OPEN_DATE
FROM
	TRANSACTIONS T
	JOIN DIM_TRANSACTION_TYPE TT ON T.TRANSACTION_TYPE_ID = TT.TRANSACTION_TYPE_ID
	JOIN DIM_MERCHANT_CATEGORY MC ON T.MERCHANT_CATEGORY_ID = MC.MERCHANT_CATEGORY_ID
	JOIN DIM_CUSTOMER C ON T.CUSTOMER_ID = C.CUSTOMER_ID;


ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN WEEKDAY TEXT;

UPDATE FACT_TRANSACTIONS
SET
	WEEKDAY = TO_CHAR(TRANSACTIONDATE, 'Day');

ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN WEEKNO TEXT;

UPDATE FACT_TRANSACTIONS
SET
	WEEKNO = 'Week ' || TO_CHAR(TRANSACTIONDATE, 'W');

ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN ACCAGE FLOAT;

UPDATE FACT_TRANSACTIONS
SET
	ACCAGE = ROUND(
		((CURRENT_DATE - ACCOUNT_OPEN_DATE) / 365.0)::NUMERIC,
		2
	);

ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN AMTBUCKET TEXT;

select min(AMOUNT_GBP), max(AMOUNT_GBP) from FACT_TRANSACTIONS;

update FACT_TRANSACTIONS
set AMTBUCKET = case
when AMOUNT_GBP < 5000 then 'Below 5000'
when 5000 <= AMOUNT_GBP and AMOUNT_GBP < 10000 then '5000 - 10000'
when 10000 <= AMOUNT_GBP and AMOUNT_GBP  < 15000 then '10000 - 15000'
when AMOUNT_GBP >= 15000 then 'Above 15000'
end;


select min(ACCAGE), max(ACCAGE) from FACT_TRANSACTIONS;

ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN accage_bucket TEXT;

update FACT_TRANSACTIONS
set accage_bucket =
CASE
    WHEN accage < 3 THEN 'New Customer (<3 Years)'
    WHEN accage < 7 THEN 'Established Customer (3-7 Years)'
    ELSE 'Long-Term Customer (7+ Years)'
END;

ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN fx_rate_check TEXT;

update fact_transactions
set fx_rate_check = case
when is_domestic = False then
	case when fx_rate_used is not null then 'FX Rate Applied'
	else 'FX Rate Not Applied'
	END
else 'Not Applicable'
end ;


select * from fact_transactions;


ALTER TABLE FACT_TRANSACTIONS
ADD COLUMN Fee_charge_check TEXT;

update FACT_TRANSACTIONS
set Fee_charge_check = 
	case 
	when fee_charged_gbp > typical_fee_gbp then 'Above Typical'
	when fee_charged_gbp < typical_fee_gbp then 'Below Typical'
	when fee_charged_gbp = typical_fee_gbp then 'Followed Standard'
else 'No Charge'
end;

select * from FACT_TRANSACTIONS;
	

